metadataId: 28c28e3a-d88f-4a34-8c60-5efe6d56a44d
output_directory: produktspesifikasjon
product_slug: arealanalyse2
updated: 2025-11-26
xmi-model: https://sosi.geonorge.no/!/#SOSI/view/head/SOSI%20Del%203/Statens%20kartverk/NasjonaltGrunnkartForArealanalyse-20260101.xml
xmi-username: sosi
xmi-password: sosi
