metadataId: 28c28e3a-d88f-4a34-8c60-5efe6d56a44d
output_directory: produktspesifikasjon
product_slug: arealanalyse3
updated: 2025-11-26
xmi_url: https://sosi.geonorge.no/svn/SOSI/SOSI Del 3/Statens kartverk/NasjonaltGrunnkartForArealanalyse-20260101.xml
xmi_username: sosi
xmi_password: sosi
